name: Java CI

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

env:
  DOCKER_URL: dcritchlow/football-dynasty-be
  JAR_NAME: footballdynasty

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests & Report
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Tests
        run: |
          mvn -B clean verify
  package:
    runs-on: ubuntu-latest
    name: Package Service
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: |
          mvn -B package \
              -Dmaven.test.skip=true \
              -DskipTests=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      - name: Set up Docker Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_URL }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=main
      - name: Set up Jar output parameters
        id: jar_params
        run: |
          set -e
          rm -f target/${{ env.JAR_NAME }}*-sources.jar
          RESOLVED_JAR_FILE="$(ls -1 target/${{ env.JAR_NAME }}*.jar)"
          echo "RESOLVED_JAR_FILE=$RESOLVED_JAR_FILE" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: | 
            JAR_FILE=${{ steps.jar_params.outputs.RESOLVED_JAR_FILE }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
